SECURITY_QUESTIONS = [
    "What was the name of your first pet?",
    "What is your mother's maiden name?",
    "What was the name of your elementary school?",
    "What is your favorite book?",
    "What city were you born in?",
    "What is your favorite food?",
    "What is your favorite color?",
    "What is your father's middle name?",
    "What was your childhood nickname?",
    "What is the name of your favorite teacher?",
    "What is your favorite movie?",
    "What is your favorite sport?",
    "What is your favorite team?",
    "What is your favorite song?",
    "What is your favorite vacation spot?",
    "What is your favorite animal?",
    "What is your favorite hobby?",
    "What is your favorite car?",
    "What is your favorite subject in school?",
    "What is your favorite season?",
    "What is your favorite holiday?",
    "What is your favorite fruit?",
    "What is your favorite vegetable?",
    "What is your favorite dessert?",
    "What is your favorite drink?",
    "What is your favorite flower?",
    "What is your favorite tree?",
    "What is your favorite number?",
    "What is your favorite quote?",
    "What is your favorite website?"
]
